name: 'Custom Greeter Action'
description: 'Custom'

inputs:
  name:
    description: 'The name of the person to greet'
    required: true
    default: 'World'

runs:
  using: 'node20'
  main: 'dist/index.js'
