name: Say Hello
run-name: ${{ github.actor }} is saying hello 👋
on: [push]

jobs:
  run-my-action:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: 'Lukas'