name: Force Transformation
run-name: ${{ github.actor }} is using the force
on: [push]

jobs:
  fetch-random:
    name: Fetch Random Character ID
    runs-on: ubuntu-latest
    outputs:
      character: ${{ steps.random-action.outputs.character_id }}    

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Random
        id: random-action
        uses: ./.github/actions/random

      - name: Print Output
        id: output
        run: echo "${{ steps.random-action.outputs.character_id }}"

  fetch-character:
    name: Fetch Character
    runs-on: ubuntu-latest
    needs: fetch-random
    outputs:
      character: ${{ steps.fetch-action.outputs.character }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Fetch
        id: fetch-action
        uses: ./.github/actions/fetch

      - name: Print Output
        id: output
        run: echo "${{ steps.fetch-action.outputs.character }}"

  greet-character:
    name: Greet Character
    runs-on: ubuntu-latest
    needs: fetch-character

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Greet
        id: greet-action
        uses: ./.github/actions/greeting
        with:
          person: ${{ needs.fetch-character.outputs.character }}

      - name: Print Output
        id: output
        run: echo "${{ steps.greet-action.outputs.greeting }}"

  build-artifact:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: fetch-character

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Output
        id: output
        run: echo "${{ needs.fetch-character.outputs.character }}"

      # Step 2: Generate some output (e.g., a file)
      - name: Generate output file
        run: echo "${{ needs.fetch-character.outputs.character }}" > output.txt

      # Step 3: Upload the output as an artifact
      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: output.txt

  use-artifact:
    name: Use Artifact
    runs-on: ubuntu-latest
    needs: build-artifact

    steps:
      # Step 1: Download the artifact
      - name: Download output artifact
        uses: actions/download-artifact@v4
        with:
          name: output-file  # Name of the artifact uploaded earlier

      # Step 2: Use the downloaded artifact
      - name: Display the content of the artifact
        run: cat output.txt
