name: Force Transformation
run-name: ${{ github.actor }} is using the force
on: [push]

jobs:
  fetch-character:
    name: Fetch Character
    runs-on: ubuntu-latest
    outputs:
      character: ${{ steps.fetch-action.outputs.character }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Fetch
        id: fetch-action
        uses: ./.github/actions/fetch

      - name: Print Output
        id: output
        run: echo "${{ steps.fetch-action.outputs.character }}"

  greet-person:
    name: Greet Person
    runs-on: ubuntu-latest
    needs: fetch-character

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Greet
        id: greet-action
        uses: ./.github/actions/greeting
        with:
          person: ${{ needs.fetch-character.outputs.character }}

      - name: Print Output
        id: output
        run: echo "${{ steps.greet-action.outputs.greeting }}"
